spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  profiles:
    active: debug
  datasource:
    druid:
      test:
        on-borrow: true
        while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mynovel?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: Gw09dianxinwb
    url: jdbc:mysql://47.112.107.122:3306/mynovel?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: myuser
    password: rvTsMakUi8#jj
  servlet:
    multipart:

      max-file-size: 100MB
      max-request-size:  1000MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  tomcat:
    uri-encoding: UTF-8
    protocol-header: upgrade
logging:
  level:
    org:
      springframework:
        security: info
    hibernate: info
  path: concretepage/logs
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
